### ISSUE TITLE
Global `never` restrictions in dist/index.d.ts break consumers whose tsc program also contains Node tooling

### ISSUE THREAD

**Issue by robinbryce** [smartcontractkit/cre-sdk-typescript#322]
Hi all,

The issue content below is agentically generated. The finding makes sense to me and we are otherwise forced to maintain local bun patches. In our model we actively want to be able to execute the workflow scripts in different toolchains. Mostly this facilitates testing, but also some ops.

Robot text follows:

---

## Summary

Since 1.19.x, importing `@chainlink/cre-sdk` anywhere in a TypeScript program marks every export of `node:fs`, `node:path`, `node:crypto`, etc. as `never`, and adds never-returning overloads of `fetch` / `setTimeout` / `setInterval`, for **every file in that program**, not only workflow files.

This comes from the two triple-slash references prepended to `dist/index.d.ts` by `scripts/src/build-types.ts`, introduced in #199:

```ts
/// <reference types="./sdk/types/restricted-apis" />
/// <reference types="./sdk/types/restricted-node-modules" />
```

Triple-slash references to files containing `declare module 'node:fs' { … }` and `declare global { … }` are global ambient declarations. TypeScript applies them to the whole program once the entry file is loaded.

## Impact

In our monorepo the workflow and its Node-side tooling (config generators, workflow-id scripts, tests, a CLI) are typechecked in the same `tsc` programs. Bumping 1.0.9 → 1.20.1 produced 161 + 138 errors of the form

```
error TS2349: This expression is not callable. Type 'never' has no call signatures.
```

on `existsSync`, `join`, `createHash`, `mkdtempSync`, `process.stdout.write`, all in files that never run in WASM. We currently ship a `bun patch` that deletes the two reference lines from `dist/index.d.ts`. It has to be refreshed on every SDK release.

Every release from 1.19.1 through 1.22.0 has the same references.

## What we agree with

We are not asking to remove the restriction. The motivation in #199 is right: Node APIs failing at WASM runtime with an opaque trace is a bad experience, and the type-level `never` markers plus the compile-time validator are a good answer for a workflow project.

## Where we respectfully push back

#199 assumes the workflow is the only code in its `tsc` program (the examples project uses `types: []` and includes only `src/**`). That does not hold for a workspace that keeps the workflow next to the scripts that build and deploy it.

The build script already acknowledges this case. `build-types.ts` injects the node-modules reference at build time rather than in `src/index.ts` because it "would break the SDK's own scripts/tests (which legitimately use Node.js APIs)". Consumers have the same shape of repository and hit the same breakage, with no equivalent escape hatch.

## Proposal

Make the restrictions opt-in rather than automatic, using the subpath export that already exists:

1. Remove the two references from the published `dist/index.d.ts`.
2. Keep `@chainlink/cre-sdk/restricted-apis` and add `@chainlink/cre-sdk/restricted-node-modules` as exported type subpaths.
3. Workflow projects enable them with a `types` entry in their `tsconfig.json`, or a triple-slash reference in the workflow entry file. `cre init` can scaffold this by default so the out-of-the-box experience is unchanged.

The compile-time validator from #199 still enforces the rule at `cre compile:workflow`, so enforcement is unchanged for the case that matters.

If you would prefer to keep the current default, an alternative is a documented opt-out such as a `@chainlink/cre-sdk/unrestricted` entry that omits the two references. Either would let us drop the patch.

Happy to open a PR for whichever direction you prefer.

## Environment

- `@chainlink/cre-sdk` 1.20.1 (also reproduced against 1.19.1, 1.21.0, 1.22.0 tarballs)
- TypeScript 5.9.3, `moduleResolution: bundler`, `skipLibCheck: true`
- bun 1.3.14
